### PR TITLE
Homework of Session 6 OOP - solved TODO #1, #2, #3

### PR DESCRIPTION
**Pull request by RF-Buerky**
after hours is was just able to solve a part of TODO #1. 

it is very difficult for me to get the hang of the codes structure.

i have an idea what causes the problem of the test closingOverdrawnAccountPaysOutNoMoney() in BankTest.kt. The limit is not correctly understood by the code so that the limit is always 0. I have no more ideas how to fix this problem.

I found the mistake by executing die following code the Main.kt
`    val bank = Bank ()

    val john = bank.newCustomer("John Doe")
    val account = bank.openAccount(john, openingDeposit = Money(100), limit = Balance(-100))
    println(account.balance) ; println( account.limit)
    println("________")
    bank.withdraw(account, Money(50))
    println(account.balance)
    println("________")
    bank.withdraw(account, Money(100))
    println(account.balance)`

So the output was

```
Balance(centAmount=100, currency=EURO)
Balance(centAmount=0, currency=EURO)
________
balance suffices, pay out the money
Balance(centAmount=50, currency=EURO)
________
insufficient balance; pay out 0
Balance(centAmount=50, currency=EURO)
```

The correct way would be something like this:

```
Balance(centAmount=100, currency=EURO)
Balance(centAmount=-100, currency=EURO)
________
balance suffices, pay out the money
Balance(centAmount=50, currency=EURO)
________
balance suffices, pay out the money
Balance(centAmount=-50, currency=EURO)
```
I would appreciate some advise.

### CODE REVIEW

**Comment by RF-Buerky** [comment]
I now found a way. I added a function to assign a new limit to accounts.

**Comment by nicolaiparlog** [comment]
Please open to PRs from master - always work in a branch.

You correctly analyzed the problem: The limit we give to the bank somehow gets lost on the way to the account. The new method can be used to fix the tests but it does not really solve the underlying problem. Have a very close look at `Bank::openAccount`. Look what happens (or rather doesn't happen) with the limit that method accepts.

**Comment by RF-Buerky** [comment]
Had noticed to late that i am on master. This will not happen again.

**Comment by nicolaiparlog** [comment]
No worries. :wink: If it does happen again, note that you can create a new branch at any time. Say you've done three commits on `master` and then realized you forgot to branch. With `git checkout -b new-branch` you can create a new branch with all your work in there. Then you only need to kill the three commits on `master`. If you're in that situation, ping me and I explain how that works.

**Comment by RF-Buerky** [comment]
I had udated my previous comment shortly after you commendet to the older version. Does github inform you about an updated comment?

**Comment by RF-Buerky** [comment]
I solved TODO #3 and tried to push it. Unfortunately this does not work

**Comment by RF-Buerky** [comment]
ups
it was not my intention to close this. Is there a way to undo this?

**Comment by RF-Buerky** [comment]
Hmm looks like a forced push destroyed it. All just because of pushing on master branch  😖

**Comment by nicolaiparlog** [comment]
>  Does github inform you about an updated comment?

Nope.

> Hmm looks like a forced push destroyed it.

It doesn't generally do that but it might happen if the pushed version is "weird".

**Comment by nicolaiparlog** [comment]
Regarding the edits to your comment...

Some terminology: A function has no constructor. A function has a name, arguments, return type (together sometimes called its _signature_), and a body. A constructor is very much like a function but will always return an instance of the class the constructor belongs to.

Then, the `limit = Balance(0)` does not mean what you think it does. It is called a [default value](https://kotlinlang.org/docs/reference/functions.html#default-arguments) and it only means that if the caller of the function does not specify a `limit`, `Balance(0)` is used for the limit. If the caller does specify a limit, then that limit is used.

But what is more important is where the `limit` goes from there. The method  `openAccount` accepts a limit but what does it do with it then?

**Comment by RF-Buerky** [comment]
Okay, thanks, very helpful explanation.

I think the mistake than is here:
val newAccount = Account()

the limit must influence the new account. so I would change this code 
line into:
val newAccount = Account(limit = limit)

after this change I can remove the following code line:
bank_setNewLimit(newAccount , limit)


Am 2017-07-27 13:40, schrieb Nicolai Parlog:

**Pull request closed without merging**
